[project]
name = "simple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.1.0",
    "uvicorn>=0.40.0",
    "websockets>=16.0",
]
